### ISSUE TITLE
Some buttons in homepage do not work

### ISSUE THREAD

**Issue by ElectricalSpace** [Historagram/historagram.github.io#1]
The buttons like "Get Source Code" and "Want To Know Me" in the homepage are not working

**Comment by Historagram** [comment]
> The buttons like "Get Source Code" and "Want To Know Me" in the homepage are not working
Sorry it was my mistake I didn't link it with the "Get Source Code". And "Want to Know Me" is purposely kept like that because I have not made it yet. Know the "Get Source Code" Button is working.
